### ISSUE TITLE
Stopping the capture object not working.

### ISSUE THREAD

**Issue by balinthanula** [antodom/tc_lib#4]
Hello Antonio,

I really like your library and im using it for an all electric instrument panel project for my car (instead of the mechanical gauges). Unfortunatly wanted to stop the capturing object with stop tc_lib.h:196 but it is not working. Action objects are used for driving stepper drivers and pulling data from the capture with get_duty_period_and_pulses tc_lib.h:164, i found out that there is an autorestart function in tc_lib.h:281 and tc_lib.h:261 which make stopping a bit useless when pulled at regular intervalls. 

Best regards
Bálint

**Comment by antodom** [comment]
Hi there Bálint,

You were right, the capture object was getting restarted, if stopped, in functions get_duty_and_period() and get_duty_period_and_pulses(). Thus, I have updated the library, in order to modify this behavior. So, if you want the capture object to not being restarted, there is now an fourth argument on both functions, do_restart (set to true by default). Setting this argument to false avoid restarting the capture object.

Please, check if it works correctly for your application.

I hope it helps.
