### ISSUE TITLE
How to stop the tc function to free up cpu resources?

### ISSUE THREAD

**Issue by BrainZhang07** [antodom/tc_lib#6]
Hi,

I am desining a fan controler with your PWM and tc library. Currently, it works great. I use PWM library to generate a PWM signal to control the fan speed and TC library to monitor the fan speed. 
I have not encountered any problem yet. But this is part of a big program. I would like to use as few CPU resources as possible. So I would like to read fan speed only when I need to. 
I have a few questions about this library.
1. Does the CPU started to count signals after I call config functions or get_duty_and_period? 
2. Will the stop() function free up the CPU resources used to monitor signal?(I already changed the do_restart to faulse)
3. If I set CAPTURE_TIME_WINDOW to a larger number(since the fan speed is not constant), will this slow down the loop time?(I use millis() instead of delay() to check speed every second)

Best Regards,
Brian

**Comment by antodom** [comment]
Hi there,

1. Does the CPU started to count signals after I call config functions or get_duty_and_period?

With the config() method the TC module starts capturing signals, but it is not the CPU doing all the work, it is mainly the TC module (in parallel). The CPU just executes interrupts generated by the TC module, each time an edge (rising or falling) is detected, or if not each time the capture window has passed by.

2. Will the stop() function free up the CPU resources used to monitor signal?(I already changed the do_restart to faulse)

Yes, the stop() method stops the capturing of signals for the TC used by your tc_lib capture object. So no more interrupts from it. The capturing stops also if too much overruns are detected, and get restarted when calling get_duty_and_period() and get_duty_period_and_pulses() functions if do_restart is true. Overruns happen when signals are to fast to follow.

3. If I set CAPTURE_TIME_WINDOW to a larger number(since the fan speed is not constant), will this slow down the loop time?(I use millis() instead of delay() to check speed every second)

What do you mean by "slow down the loop time"? The capture time window basically establish the maximum pulse duration it is possible to measure with your tc_lib capture object. If the signal you are measuring is scarce in pulses, less interrupts will be generated.

I hope it helps.
